build:
    nodes:
        analysis:
            tests:
                override: 
                    - php-scrutinizer-run
                        command: './bin/phing unit'
                        coverage:
                            file: 'test/coverage.xml'
                            format: 'php-clover'
